CREATE DATABASE QUANLYCUAHANGTIMO

GO

USE QUANLYCUAHANGTIMO

GO

CREATE TABLE VITRI(
	MAVITRI INT IDENTITY(1,1) PRIMARY KEY,
	TENVITRI NVARCHAR(100)
)

GO

CREATE TABLE BANAN
(
	MABANAN INT IDENTITY(1,1) PRIMARY KEY,
	TENBAN NVARCHAR(50),
	VITRI INT FOREIGN KEY (VITRI) REFERENCES VITRI(MAVITRI),
	TRANGTHAI BIT DEFAULT 1 --1:TRONG , 0:CO NGUOI
) 

GO

CREATE TABLE CHUCVU(
	MACHUCVU INT IDENTITY(1,1) PRIMARY KEY,
	TENCHUCVU NVARCHAR(50)
)

GO

CREATE TABLE NHANVIEN
(
	MANV INT IDENTITY(1,1) PRIMARY KEY,
	TENNV NVARCHAR(100),
	NGAYSINH DATE,
	GIOITINH BIT DEFAULT 1,--1:NAM , 0:NU
	NGAYVAOLAM DATE,
	MACHUCVU INT FOREIGN KEY (MACHUCVU) REFERENCES CHUCVU(MACHUCVU),
	SODIENTHOAI VARCHAR(10),
	DIACHI NTEXT,
	TRANGTHAI BIT DEFAULT 1
)

GO


CREATE TABLE LOAITAIKHOAN(
	MALOAI INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(50)
)

CREATE TABLE TAIKHOAN
(
	TENDANGNHAP VARCHAR(50) PRIMARY KEY,
	MATKHAU VARCHAR(50),
	MANV int foreign key (MANV) references NHANVIEN(MANV),
	LOAITAIKHOAN INT FOREIGN KEY(LOAITAIKHOAN) REFERENCES LOAITAIKHOAN(MALOAI), --1:NHAN VIEN BAN HANG 0:QUAN LY (ADMIN) 
	TRANGTHAI BIT DEFAULT 1
)

GO




CREATE TABLE DANHMUC
(
	MADANHMUC INT IDENTITY(1,1) PRIMARY KEY,
	TENDANHMUC NVARCHAR(50)
)

GO

CREATE TABLE SANPHAM
(
	MASANPHAM VARCHAR(10) PRIMARY KEY,
	TENSANPHAM NVARCHAR(100),
	DANHMUC INT FOREIGN KEY(DANHMUC) REFERENCES DANHMUC(MADANHMUC),
	SOLUONG INT,
	DONGIA MONEY,
	MOTA NTEXT,
	TRANGTHAI BIT DEFAULT 1
)

GO

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) PRIMARY KEY,
	TENKH NVARCHAR(100),
	SODIENTHOAI VARCHAR(10),
	TRANGTHAI BIT DEFAULT 1
)

GO

CREATE TABLE KICHTHUOC 
(
	MAKICHTHUOC INT IDENTITY(1,1) PRIMARY KEY,
	TENKICHTHUOC NVARCHAR(50),
	GIA MONEY,
	TRANGTHAI BIT DEFAULT 1
)

GO

CREATE TABLE HOADON
(
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAYLAPHD DATETIME,
	MANHANVIEN INT FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANV),
	MAKHACHHANG VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	SOBAN INT FOREIGN KEY(SOBAN) REFERENCES BANAN(MABANAN),
	TRANGTHAITHANHTOAN BIT DEFAULT 0,
	TRANGTHAI BIT DEFAULT 1
)

GO

CREATE TABLE CHITIETHOADON
(
	MAHD VARCHAR(10) FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	MASP VARCHAR(10) FOREIGN KEY (MASP) REFERENCES SANPHAM(MASANPHAM),
	KICHTHUOC INT FOREIGN KEY(KICHTHUOC) REFERENCES KICHTHUOC(MAKICHTHUOC),
	SOLUONG INT DEFAULT 1,
	THANHTIEN MONEY,
	TRANGTHAI BIT DEFAULT 1,
	PRIMARY KEY(MAHD,MASP)
)
